name: Pull request verify workflow

on:
  # Trigger the workflow on push or pull request,
  # but only for the default(master) branch
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, labeled, synchronize, ready_for_review]

jobs:
  checks:
    runs-on: macos-latest
    env:
      # dont treat warning as error
      CI: false

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm install

      - name: Run Lint Check
        run: npm run lint

      - name: Run Build Check
        run: npm run build

      - name: Run dist-win-unpruned Check
        run: npm run dist-win-unpruned

      - name: Run dist-mac Check
        run: npm run dist-mac

      - name: Run dist-linux Check
        run: npm run dist-linux

      - name: Annotate Checks
        uses: agyemanjp/ci-checks-action@2.0.3
        with:
          checks: '[
            {
              "name": "build",
              "fileName": ".build-report.json",
              "prChangesOnly": true
            },
            {
              "name": "lint",
              "fileName": ".lint-report.json",
              "prChangesOnly": true
            }
          ]'
